<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="OPTIMUSPRIME" failures="1" tests="8" name="Official Module" time="0.152" errors="0" timestamp="06 Apr 2022 15:44:25 GMT">
  <testcase classname="test.day3" name="loginUser" time="0.006">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at test.day3.loginUser(day3.java:21)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
... Removed 20 stack frames]]>
    </failure>
  </testcase> <!-- loginUser -->
  <testcase classname="test.day3" name="submit" time="0.01"/>
  <testcase classname="test.day3" name="submit" time="0.003"/>
  <testcase classname="test.day3" name="submit" time="0.01"/>
  <testcase classname="test.day4" name="Taxcollectorlogin" time="0.002"/>
  <testcase classname="test.day4" name="putInsepctionReport" time="0.003"/>
  <testcase classname="test.day4" name="submitReport" time="0.004"/>
  <testcase classname="test.day3" name="loginOfficial" time="0.003"/>
</testsuite> <!-- Official Module -->
